apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-7qzm
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-bundle-tenant/appstudio/dc-metro-map-7qzm@sha256:3ed2b3f5001ff4516328adf58b267563287598dfc7e31a38efcace011c0a011d
        name: my-nodejs
        resources: {}
status: {}
